baseURL: www.clouddatascience.org/
languageCode: en-us
title: Cloud-Based Data Science
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logos/logo4.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Cloud-Based Data Science
    # Hero subtitle (optional)
    subtitle: Chromebook Data Science (CBDS) is a free, massive open online educational program offered through Leanpub to help anyone who can read, write and use a computer to move into data science, the number one rated job.
    # Button text
    buttontext: Take our courses today!
    # Where the main hero button links to
    buttonlink: "https://leanpub.com/universities/set/jhu/chromebook-data-science"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - hebcac.png
    - rstudio.png
    - leanpub.png
    - datacamp.png 
    - starbucks.png
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: /
  - title: Resources
    url: /_book/index.html/
  - title: Contact
    url: /
    #sublinks:
    #- title: Dropdown item
    #  url: /
    #- title: Dropdown item
    #  url: /
    #- title: Dropdown item
    #  url: /
  - title: Donate
    url: https://www.patreon.com/
    button: true
  #sidebar:
    # Logo (from /images/logos/___.svg)
  #  logo: fresh-square
  #  sections:
  #  - title: User
  #    icon: user
  #    links:
  #    - text: Profile
  #      url: /
  #    - text: Account
  #      url: /
  #    - text: Settings
  #      url: /
  #  - title: Messages
  #    icon: envelope
  #    links:
  #    - text: Inbox
  #      url: /
  #    - text: Compose
  #      url: /
  #  - title: Images
  #    icon: image
  #    links:
  #    - text: Library
  #      url: /
  #    - text: Upload
  #      url: /
  #  - title: Settings
  #    icon: cog
  #    links:
  #    - text: User settings
  #      url: /
  #    - text: App settings
  #      url: /
  section2:
    title: Our Approach
    subtitle:  
    features:
    - title: We minimize computer costs
      text: We have developed an online program that lets students do data science using only a web browser and cheap computers like Chromebooks.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
      buttonText: Learn more about Google Chromebook
      url: https://www.google.com/chromebook/
    - title: Free Courses
      text: Our CBDS program is entirely online and you can take it for free. You can take the classes any time and at your own pace. You get a certificate for each CBDS online class from Leanpub.
      icon: doc-sync
      buttonText: See our curriculum
      url: https://leanpub.com/universities/set/jhu/chromebook-data-science/
    - title: Learn anywhere
      text: Data science work can be done from anywhere there is an Internet connection. CBDS can be completed from anywhere.
      icon: mobile-feed
      buttonText: gh
      url: /
    - title: Fiding Jobs
      text: Our program covers soft skills you need to get data science jobs, including how to network and get your name out there. We are also interested in working with partner companies who need to fill data science roles to place our graduates in remote and local data science jobs. (If you are looking for data scientists consider becoming a CBDS hiring partner).
      icon: mobile-feed
      buttonText: gh
      url: /
  section3:
    title: One Curriculum
    subtitle: The set of 11 courses
    image: illustrations/mockups/logo-01.png
    buttonText: Take our courses today!
    buttonLink: "https://leanpub.com/universities/set/jhu/chromebook-data-science"
  section4:
    title: Our Team
    subtitle: 
    clients:
    - name: Jeff Leek
      quote: Jeff Leek is the Director of the CBDS+ program. He is also a professor of biostatistics and the co-director of the Data Science Lab at Johns Hopkins University Bloomberg School of Public Health. 
      job: 
      img: jeff.png
    - name: Ashley Johnson
      quote: Ashley K.G. Johnson is the Program Administrator for CBDS+ She facilitates tutoring for program participants, manages recruitment efforts and the development of corporate and non-profit partnerships.
      job: 
      img: ashley.png
    - name: Aboozar Hadavand
      quote: Aboozar Hadavand is the Curriculum Lead for CBDS+. He is also a postdoctoral fellow at Johns Hopkins Bloomberg School of Public Health. He has previously taught at Barnard College and Brooklyn College.
      job: 
      img: aboozar.jpg
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    #socialmedia:
    #- link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      #icon: github
    #- link: https://facebook.com/#
    #  icon: facebook
    #- link: https://twitter.com/lucperkins
    #  icon: twitter
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why?
          link: /
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /
        - text: Tech articles
          link: /